GET http://localhost:3000/posts
Authorization:Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYyMDE2NTV9.gw9nwzbRNSPdjHXqdzxG-he4KRMmX1vV76vkuLmLLxw"
###

POST http://localhost:3000/login

Content-Type: application/json

{
  "username":"Kyle"
}