GET http://localhost:3000/posts
Authorization:Bearer
.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTcxNjIwOTM1Nn0.-5D1mb_CkVs4kdZwKTCNy5kbRYj59U3aPh9j2138dko

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username":"Kyle"
}