const products = [
  {
    name: "Samsung Galaxy S21",
    image: "/images/samsung-galaxy-s21.jpg",
    brand: "Samsung",
    category: "Electronics",
    description: "Latest Samsung Galaxy S21 smartphone with 8GB RAM and 128GB storage.",
    reviews: [],
    rating: 4.5,
    numReviews: 120,
    price: 799.99,
    countInStock: 50,
  },
  {
    name: "Nike Air Max 270",
    image: "/images/nike-air-max-270.jpg",
    brand: "Nike",
    category: "Footwear",
    description: "Comfortable and stylish Nike Air Max 270 sneakers.",
    reviews: [],
    rating: 4.7,
    numReviews: 200,
    price: 149.99,
    countInStock: 80,
  },
  {
    name: "Apple MacBook Pro",
    image: "/images/macbook-pro.jpg",
    brand: "Apple",
    category: "Computers",
    description: "Apple MacBook Pro with M1 chip, 16GB RAM, and 512GB SSD.",
    reviews: [],
    rating: 4.8,
    numReviews: 95,
    price: 1999.99,
    countInStock: 30,
  },
  {
    name: "Sony WH-1000XM4",
    image: "/images/sony-wh-1000xm4.jpg",
    brand: "Sony",
    category: "Electronics",
    description: "Sony noise-canceling wireless headphones with superior sound quality.",
    reviews: [],
    rating: 4.6,
    numReviews: 150,
    price: 349.99,
    countInStock: 60,
  },
  {
    name: "The North Face Borealis Backpack",
    image: "/images/north-face-borealis.jpg",
    brand: "The North Face",
    category: "Accessories",
    description: "Durable and spacious backpack for outdoor adventures.",
    reviews: [],
    rating: 4.5,
    numReviews: 85,
    price: 89.99,
    countInStock: 120,
  },
  {
    name: "Fitbit Charge 4",
    image: "/images/fitbit-charge-4.jpg",
    brand: "Fitbit",
    category: "Wearables",
    description: "Advanced fitness tracker with built-in GPS and heart rate monitor.",
    reviews: [],
    rating: 4.3,
    numReviews: 110,
    price: 129.99,
    countInStock: 90,
  },
  {
    name: "Instant Pot Duo 7-in-1",
    image: "/images/instant-pot-duo.jpg",
    brand: "Instant Pot",
    category: "Kitchen Appliances",
    description: "Multi-functional pressure cooker for quick and easy meals.",
    reviews: [],
    rating: 4.7,
    numReviews: 140,
    price: 99.99,
    countInStock: 70,
  },
  {
    name: "Canon EOS R6",
    image: "/images/canon-eos-r6.jpg",
    brand: "Canon",
    category: "Cameras",
    description:
      "High-performance mirrorless camera with 4K video recording capabilities.",
    reviews: [],
    rating: 4.9,
    numReviews: 65,
    price: 2499.99,
    countInStock: 25,
  },
  {
    name: "KitchenAid Stand Mixer",
    image: "/images/kitchenaid-stand-mixer.jpg",
    brand: "KitchenAid",
    category: "Kitchen Appliances",
    description: "Versatile stand mixer for all your baking and cooking needs.",
    reviews: [],
    rating: 4.8,
    numReviews: 100,
    price: 399.99,
    countInStock: 45,
  },
  {
    name: "Patagonia Nano Puff Jacket",
    image: "/images/patagonia-nano-puff.jpg",
    brand: "Patagonia",
    category: "Clothing",
    description: "Lightweight and warm insulated jacket for outdoor activities.",
    reviews: [],
    rating: 4.6,
    numReviews: 75,
    price: 199.99,
    countInStock: 55,
  },
]
export default products
